/* Voix Amélie (ElevenLabs) — un MP3 par animal. */
var AUDIO_MAP = {
  "Panda roux": "audio/panda-roux.mp3",
  "Manchot Adélie": "audio/manchot-adelie.mp3",
  "Léopard des neiges": "audio/leopard-des-neiges.mp3",
  "Axolotl": "audio/axolotl.mp3",
  "Fennec": "audio/fennec.mp3",
  "Kangourou roux": "audio/kangourou-roux.mp3",
  "Toucan toco": "audio/toucan-toco.mp3",
  "Renard arctique": "audio/renard-arctique.mp3",
  "Panda géant": "audio/panda-geant.mp3",
  "Paresseux à trois doigts": "audio/paresseux.mp3",
  "Narval": "audio/narval.mp3",
  "Okapi": "audio/okapi.mp3",
  "Girafe de Rothschild": "audio/girafe-de-rothschild.mp3",
  "Éléphant d'Afrique": "audio/elephant-d-afrique.mp3",
  "Rhinocéros blanc": "audio/rhinoceros-blanc.mp3",
  "Zèbre de Grant": "audio/zebre-de-grant.mp3",
  "Autruche d'Afrique": "audio/autruche-d-afrique.mp3",
  "Lion d'Afrique": "audio/lion-d-afrique.mp3",
  "Mandrill": "audio/mandrill.mp3",
  "Gorille des plaines de l'ouest": "audio/gorille-des-plaines-de-l-ouest.mp3",
  "Hippopotame commun": "audio/hippopotame-commun.mp3",
  "Potamochère roux": "audio/potamochere-roux.mp3",
  "Marabout d'Afrique": "audio/marabout-d-afrique.mp3",
  "Grue royale": "audio/grue-royale.mp3",
  "Lémur catta": "audio/lemur-catta.mp3",
  "Lémur vari": "audio/lemur-vari.mp3",
  "Colobe guéréza": "audio/colobe-guereza.mp3",
  "Suricate": "audio/suricate.mp3",
  "Porc-épic du Cap": "audio/porc-epic-du-cap.mp3",
  "Daman des rochers": "audio/daman-des-rochers.mp3",
  "Gnou bleu": "audio/gnou-bleu.mp3",
  "Loutre à joues blanches du Cap": "audio/loutre-a-joues-blanches-du-cap.mp3",
  "Oryx de Libye": "audio/oryx-de-libye.mp3",
  "Éland du Cap": "audio/eland-du-cap.mp3",
  "Gazelle de Thomson": "audio/gazelle-de-thomson.mp3",
  "Flamant des Caraïbes": "audio/flamant-des-caraibes.mp3",
  "Macaque japonais": "audio/macaque-japonais.mp3",
  "Tigre de l'Amour": "audio/tigre-de-l-amour.mp3",
  "Léopard de l'Amour": "audio/leopard-de-l-amour.mp3",
  "Chameau de Bactriane": "audio/chameau-de-bactriane.mp3",
  "Yack domestique": "audio/yack-domestique.mp3",
  "Ours noir de l'Himalaya": "audio/ours-noir-de-l-himalaya.mp3",
  "Thar de l'Himalaya": "audio/thar-de-l-himalaya.mp3",
  "Dhole": "audio/dhole.mp3",
  "Grue du Japon": "audio/grue-du-japon.mp3",
  "Saro du Japon": "audio/saro-du-japon.mp3",
  "Kangourou gris de l'Est": "audio/kangourou-gris-de-l-est.mp3",
  "Wallaby de Bennett": "audio/wallaby-de-bennett.mp3",
  "Émeu d'Australie": "audio/emeu-d-australie.mp3",
  "Cygne noir": "audio/cygne-noir.mp3",
  "Loriquet à tête bleue": "audio/loriquet-a-tete-bleue.mp3",
  "Tortue verte": "audio/tortue-verte.mp3",
  "Requin à pointes noires": "audio/requin-a-pointes-noires.mp3",
  "Hippocampe à gros ventre": "audio/hippocampe-a-gros-ventre.mp3",
  "Renard volant géant": "audio/renard-volant-geant.mp3",
  "Jaguar": "audio/jaguar.mp3",
  "Capybara": "audio/capybara.mp3",
  "Paresseux à deux doigts": "audio/paresseux-a-deux-doigts.mp3",
  "Tatou à trois bandes": "audio/tatou-a-trois-bandes.mp3",
  "Callimico de Goeldi": "audio/callimico-de-goeldi.mp3",
  "Condor des Andes": "audio/condor-des-andes.mp3",
  "Lama": "audio/lama.mp3",
  "Ocelot": "audio/ocelot.mp3",
  "Anaconda vert": "audio/anaconda-vert.mp3",
  "Alligator américain": "audio/alligator-americain.mp3",
  "Tortue molle à épines": "audio/tortue-molle-a-epines.mp3",
  "Grenouille dorée du Panama": "audio/grenouille-doree-du-panama.mp3",
  "Python réticulé": "audio/python-reticule.mp3",
  "Cerf de Virginie": "audio/cerf-de-virginie.mp3",
  "Wapiti": "audio/wapiti.mp3",
  "Bison d'Amérique": "audio/bison-d-amerique.mp3",
  "Ours noir d'Amérique": "audio/ours-noir-d-amerique.mp3",
  "Chèvre domestique": "audio/chevre-domestique.mp3",
  "Âne domestique": "audio/ane-domestique.mp3",
  "Canard domestique": "audio/canard-domestique.mp3",
  "Ours blanc": "audio/ours-blanc.mp3",
  "Bœuf musqué": "audio/b-uf-musque.mp3",
  "Carcajou": "audio/carcajou.mp3",
  "Caribou des bois": "audio/caribou-des-bois.mp3",
  "Harfang des neiges": "audio/harfang-des-neiges.mp3",
  "Cygne trompette": "audio/cygne-trompette.mp3",
  "Bernache du Canada": "audio/bernache-du-canada.mp3",
  "Oie des neiges": "audio/oie-des-neiges.mp3",
  "Loutre de rivière": "audio/loutre-de-riviere.mp3",
  "Lynx du Canada": "audio/lynx-du-canada.mp3",
  "Martre d'Amérique": "audio/martre-d-amerique.mp3",
  "Orignal": "audio/orignal.mp3",
  "Pékan": "audio/pekan.mp3",
  "Grand Corbeau": "audio/grand-corbeau.mp3",
  "Pygargue à tête blanche": "audio/pygargue-a-tete-blanche.mp3",
  "Couguar": "audio/couguar.mp3",
  "Chèvre de montagne": "audio/chevre-de-montagne.mp3",
  "Mouflon canadien": "audio/mouflon-canadien.mp3",
  "Mouflon de Dall": "audio/mouflon-de-dall.mp3",
  "Grizzli": "audio/grizzli.mp3",
  "Urubu à tête rouge": "audio/urubu-a-tete-rouge.mp3",
  "Gélada": "audio/gelada.mp3",
  "Bihoreau gris": "audio/bihoreau-gris.mp3",
  "Buse à queue rousse": "audio/buse-a-queue-rousse.mp3",
  "Butor d'Amérique": "audio/butor-d-amerique.mp3",
  "Castor du Canada": "audio/castor-du-canada.mp3",
  "Coyote": "audio/coyote.mp3",
  "Dindon sauvage": "audio/dindon-sauvage.mp3",
  "Grand Héron": "audio/grand-heron.mp3",
  "Loup gris": "audio/loup-gris.mp3",
  "Lynx roux": "audio/lynx-roux.mp3",
  "Mouffette rayée": "audio/mouffette-rayee.mp3",
  "Porc-épic d'Amérique": "audio/porc-epic-d-amerique.mp3",
  "Rat musqué": "audio/rat-musque.mp3",
  "Raton laveur": "audio/raton-laveur.mp3",
  "Renard roux": "audio/renard-roux.mp3",
  "Antilope d'Amérique": "audio/antilope-d-amerique.mp3",
  "Bison des bois": "audio/bison-des-bois.mp3",
  "Buse pattue": "audio/buse-pattue.mp3",
  "Cerf mulet": "audio/cerf-mulet.mp3",
  "Chevêche des terriers": "audio/cheveche-des-terriers.mp3",
  "Chien de prairie à queue noire": "audio/chien-de-prairie-a-queue-noire.mp3",
  "Couleuvre rayée": "audio/couleuvre-rayee.mp3",
  "Grue du Canada": "audio/grue-du-canada.mp3",
  "Cheval de Przewalski": "audio/cheval-de-przewalski.mp3",
  "Grue demoiselle": "audio/grue-demoiselle.mp3",
  "Oie à tête barrée": "audio/oie-a-tete-barree.mp3",
  "Oie cygnoïde": "audio/oie-cygnoide.mp3",
  "Tadorne casarca": "audio/tadorne-casarca.mp3",
  "Bouquetin de Sibérie": "audio/bouquetin-de-siberie.mp3",
  "Marmotte commune": "audio/marmotte-commune.mp3",
  "Canard colvert": "audio/canard-colvert.mp3",
  "Vache domestique": "audio/vache-domestique.mp3",
  "Poule domestique": "audio/poule-domestique.mp3",
  "Oie domestique": "audio/oie-domestique.mp3",
  "Lapin européen": "audio/lapin-europeen.mp3",
  "Lapin de Floride": "audio/lapin-de-floride.mp3",
  "Lièvre d'Amérique": "audio/lievre-d-amerique.mp3",
  "Lièvre arctique": "audio/lievre-arctique.mp3"
};
