/* Statut de conservation (Liste rouge UICN) — code par animal. */
var STATUS_MAP = {
  "Panda roux": "EN",
  "Manchot Adélie": "LC",
  "Léopard des neiges": "VU",
  "Axolotl": "CR",
  "Fennec": "LC",
  "Kangourou roux": "LC",
  "Toucan toco": "LC",
  "Renard arctique": "LC",
  "Panda géant": "VU",
  "Paresseux à trois doigts": "LC",
  "Narval": "LC",
  "Okapi": "EN",
  "Girafe de Rothschild": "VU",
  "Éléphant d'Afrique": "EN",
  "Rhinocéros blanc": "NT",
  "Zèbre de Grant": "NT",
  "Autruche d'Afrique": "LC",
  "Lion d'Afrique": "VU",
  "Mandrill": "VU",
  "Gorille des plaines de l'ouest": "CR",
  "Hippopotame commun": "VU",
  "Potamochère roux": "LC",
  "Marabout d'Afrique": "LC",
  "Grue royale": "EN",
  "Lémur catta": "EN",
  "Lémur vari": "CR",
  "Colobe guéréza": "LC",
  "Suricate": "LC",
  "Porc-épic du Cap": "LC",
  "Daman des rochers": "LC",
  "Gnou bleu": "LC",
  "Loutre à joues blanches du Cap": "NT",
  "Oryx de Libye": "EW",
  "Éland du Cap": "LC",
  "Gazelle de Thomson": "LC",
  "Flamant des Caraïbes": "LC",
  "Macaque japonais": "LC",
  "Tigre de l'Amour": "EN",
  "Léopard de l'Amour": "CR",
  "Chameau de Bactriane": "CR",
  "Yack domestique": "DO",
  "Ours noir de l'Himalaya": "VU",
  "Thar de l'Himalaya": "NT",
  "Dhole": "EN",
  "Grue du Japon": "VU",
  "Saro du Japon": "LC",
  "Kangourou gris de l'Est": "LC",
  "Wallaby de Bennett": "LC",
  "Émeu d'Australie": "LC",
  "Cygne noir": "LC",
  "Loriquet à tête bleue": "LC",
  "Tortue verte": "EN",
  "Requin à pointes noires": "VU",
  "Hippocampe à gros ventre": "LC",
  "Renard volant géant": "EN",
  "Jaguar": "NT",
  "Capybara": "LC",
  "Paresseux à deux doigts": "LC",
  "Tatou à trois bandes": "NT",
  "Callimico de Goeldi": "VU",
  "Condor des Andes": "VU",
  "Lama": "DO",
  "Ocelot": "LC",
  "Anaconda vert": "LC",
  "Alligator américain": "LC",
  "Tortue molle à épines": "LC",
  "Grenouille dorée du Panama": "CR",
  "Python réticulé": "LC",
  "Cerf de Virginie": "LC",
  "Wapiti": "LC",
  "Bison d'Amérique": "NT",
  "Ours noir d'Amérique": "LC",
  "Chèvre domestique": "DO",
  "Âne domestique": "DO",
  "Canard domestique": "DO",
  "Ours blanc": "VU",
  "Bœuf musqué": "LC",
  "Carcajou": "LC",
  "Caribou des bois": "VU",
  "Harfang des neiges": "VU",
  "Cygne trompette": "LC",
  "Bernache du Canada": "LC",
  "Oie des neiges": "LC",
  "Loutre de rivière": "LC",
  "Lynx du Canada": "LC",
  "Martre d'Amérique": "LC",
  "Orignal": "LC",
  "Pékan": "LC",
  "Grand Corbeau": "LC",
  "Pygargue à tête blanche": "LC",
  "Couguar": "LC",
  "Chèvre de montagne": "LC",
  "Mouflon canadien": "LC",
  "Mouflon de Dall": "LC",
  "Grizzli": "LC",
  "Urubu à tête rouge": "LC",
  "Gélada": "LC",
  "Bihoreau gris": "LC",
  "Buse à queue rousse": "LC",
  "Butor d'Amérique": "LC",
  "Castor du Canada": "LC",
  "Coyote": "LC",
  "Dindon sauvage": "LC",
  "Grand Héron": "LC",
  "Loup gris": "LC",
  "Lynx roux": "LC",
  "Mouffette rayée": "LC",
  "Porc-épic d'Amérique": "LC",
  "Rat musqué": "LC",
  "Raton laveur": "LC",
  "Renard roux": "LC",
  "Antilope d'Amérique": "LC",
  "Bison des bois": "NT",
  "Buse pattue": "LC",
  "Cerf mulet": "LC",
  "Chevêche des terriers": "LC",
  "Chien de prairie à queue noire": "LC",
  "Couleuvre rayée": "LC",
  "Grue du Canada": "LC",
  "Cheval de Przewalski": "EN",
  "Grue demoiselle": "LC",
  "Oie à tête barrée": "LC",
  "Oie cygnoïde": "VU",
  "Tadorne casarca": "LC",
  "Bouquetin de Sibérie": "NT",
  "Marmotte commune": "LC",
  "Canard colvert": "LC",
  "Vache domestique": "DO",
  "Poule domestique": "DO",
  "Oie domestique": "DO",
  "Lapin européen": "EN",
  "Lapin de Floride": "LC",
  "Lièvre d'Amérique": "LC",
  "Lièvre arctique": "LC"
};
